# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    verify-gradle-wrapper:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: gradle/wrapper-validation-action@8d49e559aae34d3e0eb16cde532684bc9702762b # v1.0.6

    build:
        if: "! contains(toJSON(github.event.commits.*.message), '[skip ci]')"
        runs-on: ubuntu-latest
        strategy:
            matrix:
                jdk: [11, 15, 16]
        steps:
            - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
            - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
              with:
                path: |
                    ~/.gradle/caches
                    ~/.gradle/wrapper
                key: ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}
                restore-keys: |
                    ${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-
            - name: Set up JDK
              uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
              with:
                  java-version: ${{ matrix.jdk }}
                  distribution: adopt
            - run: ./gradlew build --stacktrace --warning-mode all

    release:
        runs-on: ubuntu-latest
        needs: [build, verify-gradle-wrapper] # build job must pass before we can release

        if: github.event_name == 'push'
            && github.ref == 'refs/heads/main'
            && github.repository == 'MinimallyCorrect/JavaTransformer'
            && !contains(toJSON(github.event.commits.*.message), '[skip ci]')
            && !contains(toJSON(github.event.commits.*.message), '[skip release]')

        steps:
            - name: Check out code
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
              with:
                  fetch-depth: '0' # https://github.com/shipkit/shipkit-changelog#fetch-depth-on-ci

            - uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
              with:
                path: |
                  ~/.gradle/caches
                  ~/.gradle/wrapper
                key: releasing-${{ runner.os }}-jdk-${{ matrix.jdk }}-gradlewrapper-${{ hashFiles('**/gradle-wrapper.properties') }}-gradlescripts-${{ hashFiles('**/*.gradle*') }}

            - name: Set up Java 11
              uses: actions/setup-java@3f07048e3d294f56e9b90ac5ea2c6f74e9ad0f98 # v3.10.0
              with:
                  java-version: 11
                  distribution: adopt

            - name: Build and publish to github
              run: ./gradlew -P releasing build publish githubRelease -s
              env:
                  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
                  DEPLOYMENT_REPO_URL_RELEASE: ${{secrets.DEPLOYMENT_REPO_URL_RELEASE}}
                  DEPLOYMENT_REPO_URL_SNAPSHOT: ${{secrets.DEPLOYMENT_REPO_URL_SNAPSHOT}}
                  DEPLOYMENT_REPO_USERNAME: ${{secrets.DEPLOYMENT_REPO_USERNAME}}
                  DEPLOYMENT_REPO_PASSWORD: ${{secrets.DEPLOYMENT_REPO_PASSWORD}}
